"use client";
import { Plus, Trash2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useToast } from "@/components/feedback/toast";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { createRiskTreatmentPlanSchema } from "../schemas/create-risk-treatment-plan-schema";
import { useCreateRiskTreatmentPlan, useRiskTreatmentPlanOptions } from "../hooks/use-create-risk-treatment-plan";

type Action = { title: string; assignedToUserId: string; dueDate: string };
export function CreateRiskTreatmentPlanDialog({ riskId, riskLabel, onClose }: { riskId: string | null; riskLabel: string; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null); const toast = useToast(); const options = useRiskTreatmentPlanOptions(Boolean(riskId)); const mutation = useCreateRiskTreatmentPlan();
  const [title, setTitle] = useState(""); const [strategy, setStrategy] = useState("mitigate"); const [owner, setOwner] = useState(""); const [targetDate, setTargetDate] = useState(""); const [targetRisk, setTargetRisk] = useState("low"); const [controls, setControls] = useState<string[]>([]); const [actions, setActions] = useState<Action[]>([{ title: "", assignedToUserId: "", dueDate: "" }]); const [error, setError] = useState("");
  useEffect(() => { if (riskId) ref.current?.showModal(); else ref.current?.close(); }, [riskId]);
  const close = () => { ref.current?.close(); onClose(); setError(""); };
  const submit = async () => { if (!riskId) return; const parsed = createRiskTreatmentPlanSchema.safeParse({ riskId, title, strategy, ownerUserId: owner, targetDate, targetRisk, controlIds: controls, actions }); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Check the plan details."); return; } try { await mutation.mutateAsync(parsed.data); toast.success("Treatment plan created", riskLabel); close(); } catch { setError("Unable to create the treatment plan. Check the data and try again."); } };
  return <Dialog title="Create Risk Treatment Plan" dialogRef={ref} onClose={close} className="max-h-[90vh] w-[min(56rem,calc(100%-2rem))] overflow-y-auto">
    <form className="space-y-5" onSubmit={(event) => { event.preventDefault(); void submit(); }}><p className="text-muted text-sm">{riskLabel}</p>{error ? <Alert className="border-danger/25 bg-danger-soft text-danger">{error}</Alert> : null}
      <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Plan title<Input className="mt-1" value={title} onChange={(e) => setTitle(e.target.value)} /></label><label className="text-sm font-medium">Treatment option<Select className="mt-1" value={strategy} onChange={(e) => setStrategy(e.target.value)}><option value="mitigate">Mitigate</option><option value="avoid">Avoid</option><option value="transfer">Transfer</option><option value="accept">Accept</option></Select></label><label className="text-sm font-medium">Responsible owner<Select className="mt-1" value={owner} onChange={(e) => setOwner(e.target.value)}><option value="">Select owner</option>{options.data?.users.map((u) => <option key={u.id} value={u.id}>{u.fullName} — {u.email}</option>)}</Select></label><label className="text-sm font-medium">Due date<Input className="mt-1" type="date" value={targetDate} onChange={(e) => setTargetDate(e.target.value)} /></label><label className="text-sm font-medium">Target risk<Select className="mt-1" value={targetRisk} onChange={(e) => setTargetRisk(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></Select></label></div>
      <fieldset className="space-y-2"><legend className="text-sm font-medium">Related controls</legend><div className="border-border grid max-h-40 gap-2 overflow-y-auto rounded-lg border p-3 md:grid-cols-2">{options.data?.controls.map((c) => <Label key={c.id} className="flex items-start gap-2"><input type="checkbox" checked={controls.includes(c.id)} onChange={(e) => setControls(e.target.checked ? [...controls, c.id] : controls.filter((id) => id !== c.id))} /><span>{c.code} — {c.name}</span></Label>)}</div></fieldset>
      <section className="space-y-3"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Required actions</h3><p className="text-muted text-sm">Acceptance plans may have no action.</p></div><Button type="button" variant="secondary" onClick={() => setActions([...actions, { title: "", assignedToUserId: "", dueDate: "" }])}><Plus className="size-4" />Add action</Button></div>{actions.map((action, index) => <div key={index} className="border-border grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_1fr_10rem_auto]"><Input aria-label={`Action ${index + 1} title`} placeholder="Action description" value={action.title} onChange={(e) => setActions(actions.map((a, i) => i === index ? { ...a, title: e.target.value } : a))} /><Select aria-label={`Action ${index + 1} owner`} value={action.assignedToUserId} onChange={(e) => setActions(actions.map((a, i) => i === index ? { ...a, assignedToUserId: e.target.value } : a))}><option value="">Assign owner</option>{options.data?.users.map((u) => <option key={u.id} value={u.id}>{u.fullName}</option>)}</Select><Input aria-label={`Action ${index + 1} due date`} type="date" value={action.dueDate} onChange={(e) => setActions(actions.map((a, i) => i === index ? { ...a, dueDate: e.target.value } : a))} /><Button type="button" variant="secondary" aria-label={`Remove action ${index + 1}`} onClick={() => setActions(actions.filter((_, i) => i !== index))}><Trash2 className="size-4" /></Button></div>)}</section>
      <div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit" disabled={mutation.isPending || options.isPending}>{mutation.isPending ? "Creating..." : "Create plan"}</Button></div></form></Dialog>;
}
