import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { cleanup } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const { push, useAssets, useSessionUser } = vi.hoisted(() => ({ push: vi.fn(), useAssets: vi.fn(), useSessionUser: vi.fn() }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ push }), useSearchParams: () => new URLSearchParams(), usePathname: () => "/assets" }));
vi.mock("../hooks/use-assets", () => ({ useAssets }));
vi.mock("@/features/authentication-account", () => ({ useSessionUser }));
vi.mock("./asset-detail-dialog", () => ({ AssetDetailDialog: () => null }));
vi.mock("./edit-asset-dialog", () => ({ EditAssetDialog: () => null }));
vi.mock("./delete-asset-dialog", () => ({ DeleteAssetDialog: () => null }));
vi.mock("./assign-asset-owner-dialog", () => ({ AssignAssetOwnerDialog: () => null }));
vi.mock("./classify-asset-criticality-dialog", () => ({ ClassifyAssetCriticalityDialog: () => null }));
vi.mock("./link-asset-context-dialog", () => ({ LinkAssetContextDialog: () => null }));
import { AssetsShell } from "./assets-shell";
afterEach(cleanup);
const response = { items: [{ id: "00000000-0000-4000-8000-000000000001", assetCode: "AST-001", name: "Core Server", assetType: "server", criticality: "high", dataClassification: "confidential", description: null, status: "active", owner: { id: "00000000-0000-4000-8000-000000000002", fullName: "Asset Owner", inactive: false }, businessService: null, createdAt: "2026-09-10T00:00:00.000Z", updatedAt: "2026-09-11T00:00:00.000Z" }], pagination: { page: 1, limit: 10, total: 1, totalPages: 1 } };
describe("AssetsShell", () => { beforeEach(() => { push.mockReset(); useSessionUser.mockReturnValue({ isPending: false, data: { permissions: ["assets.read"] } }); useAssets.mockReturnValue({ isPending: false, isError: false, data: response, refetch: vi.fn() }); });
  it("renders the V2 asset directory", () => { render(<AssetsShell />); expect(screen.getByText("Core Server")).toBeInTheDocument(); expect(screen.getByText("Asset Owner")).toBeInTheDocument(); expect(screen.getByText("confidential")).toBeInTheDocument(); });
  it("groups asset actions in an overflow menu", async () => { useSessionUser.mockReturnValue({ isPending: false, data: { permissions: ["assets.read", "assets.update"] } }); render(<AssetsShell />); expect(screen.queryByRole("button", { name: "Assign owner" })).not.toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Actions for AST-001" })); expect(screen.getByRole("button", { name: "View details" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Edit asset" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Manage links" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Classify asset" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Assign owner" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Archive asset" })).toBeInTheDocument(); });
  it("only allows viewing an archived asset", async () => { useSessionUser.mockReturnValue({ isPending: false, data: { permissions: ["assets.read", "assets.update"] } }); useAssets.mockReturnValue({ isPending: false, isError: false, data: { ...response, items: [{ ...response.items[0], status: "archived" }] }, refetch: vi.fn() }); render(<AssetsShell />); await userEvent.click(screen.getByRole("button", { name: "Actions for AST-001" })); expect(screen.getByRole("button", { name: "View details" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Edit asset" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Manage links" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Classify asset" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Assign owner" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Archive asset" })).not.toBeInTheDocument(); });
  it("writes bounded filters to the URL", async () => { render(<AssetsShell />); const user = userEvent.setup(); await user.type(screen.getByLabelText("Search"), "server"); await user.click(screen.getByRole("button", { name: "Filter" })); expect(push).toHaveBeenCalledWith(expect.stringContaining("q=server")); });
  it("shows an authorization state without querying", () => { useSessionUser.mockReturnValue({ isPending: false, data: { permissions: [] } }); render(<AssetsShell />); expect(screen.getByText("You do not have permission to view assets")).toBeInTheDocument(); });
});
