"use client";
import { Download, FileCheck2, Search, Upload } from "lucide-react";
import { useRef, useState, type FormEvent } from "react";
import { DataTable, type DataTableColumn } from "@/components/data-display/data-table";
import { Pagination } from "@/components/data-display/pagination";
import { ProductPageHeader, ProductPanel, StatusBadge } from "@/components/data-display/static-product";
import { EmptyState } from "@/components/feedback/empty-state";
import { useToast } from "@/components/feedback/toast";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useSessionUser } from "@/features/auth";
import { useEvidenceAssessments, useUploadEvidence } from "../hooks/use-compliance-evidence";
import type { EvidenceAssessment } from "../schemas/compliance-evidence-schema";

const formatDate = (value: string) => new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value));
const formatBytes = (value: number | null) => value === null ? "Unknown size" : value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`;
export function ComplianceEvidenceManager() {
  const session = useSessionUser(); const allowed = session.data?.permissions.includes("compliance.evidence.upload") ?? false;
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [q, setQ] = useState<string>(); const query = useEvidenceAssessments({ page, limit: 20, ...(q ? { q } : {}) }, allowed);
  const [selected, setSelected] = useState<EvidenceAssessment>(); const [file, setFile] = useState<File>(); const [description, setDescription] = useState(""); const [validUntil, setValidUntil] = useState(""); const [error, setError] = useState<string>(); const dialog = useRef<HTMLDialogElement>(null); const mutation = useUploadEvidence(); const toast = useToast();
  const open = (item: EvidenceAssessment) => { setSelected(item); setFile(undefined); setDescription(""); setValidUntil(""); setError(undefined); dialog.current?.showModal(); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!selected || !file) { setError("Choose an evidence file before uploading."); return; } if (file.size > 10 * 1024 * 1024) { setError("Evidence files may not exceed 10 MB."); return; } setError(undefined); try { const cleanDescription = description.trim(); await mutation.mutateAsync({ assessmentId: selected.id, file, ...(cleanDescription ? { description: cleanDescription } : {}), ...(validUntil ? { validUntil } : {}) }); dialog.current?.close(); toast.success("Evidence uploaded", `${file.name} is now linked to ${selected.control.code}.`); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Unable to upload evidence."); } };
  const columns: readonly DataTableColumn<EvidenceAssessment>[] = [
    { key: "control", header: "Control assessment", cell: (item) => <span className="block min-w-56"><strong className="block">{item.control.title}</strong><span className="text-muted text-xs">{item.control.code} · {item.control.framework.code}{item.control.framework.version ? ` ${item.control.framework.version}` : ""}</span></span> },
    { key: "result", header: "Result", cell: (item) => <span><StatusBadge tone={item.complianceStatus === "compliant" ? "success" : item.complianceStatus === "non_compliant" ? "danger" : "warning"}>{item.complianceStatus.replaceAll("_", " ")}</StatusBadge><span className="text-muted mt-1 block text-xs">Assessed {formatDate(item.assessedAt)}</span></span> },
    { key: "evidence", header: "Evidence", cell: (item) => item.evidence.length ? <ul className="max-w-md space-y-2">{item.evidence.map((evidence) => <li className="flex items-center justify-between gap-3" key={evidence.id}><span className="min-w-0"><span className="block truncate font-medium" title={evidence.file.name}>{evidence.file.name}</span><span className="text-muted text-xs">{formatBytes(evidence.file.sizeBytes)} · {evidence.uploadedBy?.name ?? "Unknown"}{evidence.validUntil ? ` · valid to ${evidence.validUntil}` : ""}</span></span><a aria-label={`Download ${evidence.file.name}`} className="text-brand inline-flex min-h-10 items-center gap-1 px-2 text-sm font-medium" href={`/api/compliance/evidence/${evidence.id}/download`}><Download className="size-4" aria-hidden="true"/>Download</a></li>)}</ul> : <span className="text-muted">No evidence uploaded</span> },
    { key: "action", header: "Action", cell: (item) => <Button variant="secondary" className="min-h-10" onClick={() => open(item)}><Upload className="size-4" aria-hidden="true"/>Upload evidence</Button> },
  ];
  if (session.isPending) return <div className="bg-neutral-soft h-56 animate-pulse rounded-xl" aria-label="Checking evidence permission"/>;
  if (!allowed) return <Alert><strong className="block">You do not have permission to upload compliance evidence</strong><span>Contact an administrator to request compliance.evidence.upload.</span></Alert>;
  return <><ProductPageHeader title="Compliance evidence" description="Upload supporting documents to accessible control assessments and review existing evidence." showSampleNotice={false}/><ProductPanel title="Control assessments" description={`${query.data?.pagination.total ?? 0} assessments available.`}><div className="space-y-4 p-5"><form className="flex flex-col gap-2 sm:flex-row" onSubmit={(event) => { event.preventDefault(); setPage(1); setQ(search.trim() || undefined); }}><div className="relative flex-1"><Search className="text-muted absolute top-1/2 left-3 size-4 -translate-y-1/2" aria-hidden="true"/><Input className="pl-9" aria-label="Search assessments" placeholder="Search by control code or title" value={search} onChange={(event) => setSearch(event.target.value)}/></div><Button type="submit"><Search className="size-4" aria-hidden="true"/>Search</Button></form>{query.isError ? <Alert>Unable to load compliance assessments. {query.error.message}</Alert> : query.isPending ? <div className="bg-neutral-soft h-64 animate-pulse rounded-xl"/> : query.data.items.length ? <DataTable columns={columns} rows={query.data.items} getRowKey={(item) => item.id}/> : <EmptyState title="No accessible assessments" description="Evidence can be uploaded after an applicable control has been assessed."/>}{query.data ? <Pagination page={page} pageCount={query.data.pagination.totalPages} onPageChange={setPage}/> : null}</div></ProductPanel>
  <Dialog dialogRef={dialog} title={selected ? `Upload evidence for ${selected.control.code}` : "Upload compliance evidence"}><form className="space-y-4" onSubmit={submit}>{error ? <Alert>{error}</Alert> : null}<div><Label htmlFor="evidence-file">Evidence file</Label><Input id="evidence-file" className="mt-1.5 file:mr-3" type="file" required accept=".pdf,.png,.jpg,.jpeg,.txt,.csv,.docx,.xlsx" onChange={(event) => setFile(event.target.files?.[0])}/><p className="text-muted mt-1 text-xs">PDF, PNG, JPEG, TXT, CSV, DOCX or XLSX; maximum 10 MB.</p></div><div><Label htmlFor="evidence-description">Description</Label><Textarea id="evidence-description" className="mt-1.5 min-h-24" maxLength={2000} value={description} onChange={(event) => setDescription(event.target.value)}/></div><div><Label htmlFor="evidence-valid-until">Valid until</Label><Input id="evidence-valid-until" className="mt-1.5" type="date" value={validUntil} onChange={(event) => setValidUntil(event.target.value)}/></div><div className="flex justify-end gap-2"><Button type="button" variant="secondary" disabled={mutation.isPending} onClick={() => dialog.current?.close()}>Cancel</Button><Button type="submit" disabled={mutation.isPending}><FileCheck2 className="size-4" aria-hidden="true"/>{mutation.isPending ? "Uploading…" : "Upload evidence"}</Button></div></form></Dialog></>;
}
